sudo: required
services:
- docker
before_install:
# Install s2i
- |
  go get github.com/openshift/source-to-image
  pushd ${GOPATH}/src/github.com/openshift/source-to-image
  export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  hack/build-go.sh
  popd
script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then DOCKER_PUSH=true && docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io; fi
- ./hack/run build
notifications:
  slack:
    secure: QkQ5KyInwOWmkk4SWw3vSyagJtHH2T5zV9BKZMyGctQNgdCkC7nlUKBcoimMPwlhh2kC/VTjQRXKsdfBAZfFYtQEj1HecxWkMYkO/NACi0r2BrU+7odvtPhwsey3guazpnkit8So1vsMWQFFjVNhYmrzobMUHuu+9E+yvImTNejjMMVGKdvUm+VwXRKjsG1pmWHs5q6nQFpZFZvrnlQyX0RbgtfbYW0T5XSjeBbBQC8VdHeTFq9JTHQgJNXmaisbtP9kWZyqGGcbrUNFuZwgV14OqVSitUSi9F2WwyiojU71ONyGuR3Eayj0ChVPJ97fMcYbhSLvolPrkM+CeNHva+Ieqd1MniFZHuKkHpTS62oE6L0cuDPK1DYlzAiZp+3y4VaSA7t4whwPkqIbvODpyORipSfqObG49wlNqEGRdEaqCxRgk9ap7gXpCW12egOhsK/HxkBbYbgcr+ruS1ycVqUgkFzMhNs1+WIqB8+gtEzNf6leTnDRkFuVjzEpUfh0bHeYddW6Z4a4OJdx7gm/sjKu8DGcEDvXm5xIvm8m+9GBAj8babR0Lceaa4izN14LWOkLmhgmDyNfd/+IOihfX/XKNau6rpMB5/gD9rWyhJOwb3rNHJ1+FXvTtEe6Pa19OFrOf9xkxSuwzaS4kaUr7XJBhRLfbR/cnidu2GT7AHI=
env:
  global:
  - secure: HdWO923lWFYCBWUvNrlXTWPd7rTth4TTvBs2tqcDMeHPD0MCalrl1cDmw5mZHcZAC4rw7v/vWOct0sYiFcyM9gbd4n7Co5Pz+7yPEx+j5tnUY8Vvy3X7J/NZuc/+llJj0LIHwk9IE5fun9hUo3yL33gzX5myIaLo6wnzkCZ79Tsh48Gk97qVMHMOndk1NyudIejTFZv7hMebme8cGV9l6Aa7BrAmPRpUIjq2Iyr2snwAmbo+PmQzFr0TrKHXvOPVjkKhwr0a2dulLcchaMyRnPGPryVusL9l74ZlCxVd8QHJewramcbhht08P3Vrf/ktMcT9Q9rDb7WvXXLwCIXzw7Q7h6UBmaBKvm8zqtW/CSOpeOXt4e90Mp2yeUpWNB3I37CVMLGu5DHMBWCqD28fTyB472aogfprYdBtrSmWhNq+X3dHBr6XXKTGC4oQPWjPnZO+SsquSdgoCUMxCsDdft/ds54HUZIUAsC3tsznzfE9F5t1nPBzc1rv8tcct5CeLo4kqpOL9uBVoV3Bj0VN9qMGP6kWIsb58A+qrubNrO7KbhHYUIcg+49RylzUBOSAPj8vSmqgcGvgp44CGcM2jr2/GaV/u7RAW0d96rTtsNN0eGHYNth8QSlL9pS6jTLMaxn69mODBaWGb0C9GqoIBqlRenGNTHGwE4WeJKRoTFc=
  - secure: c177f63yNc5Yzf9C7ytm9W3qWaHrXxrukFfNRIu6jKgUTERGt8rfCdrouvtew84oDINvLQzDy54KNF38TR9LZkXsCp4jVU4TaG10r5QH+8Yqhy1LXDaNEBfMKb7J6XSS5n0NHKuP25/CHI3I/jDjlbtuWY1OY5fVg6fVoN24Ll+RlEd9y5XZQ1mQoKU/Qrxplg6AcTrHvFHgQBngl4cyiDvcekaxGGSL9pI2gombe6hLt4v90JXC7zuhAZGXaivDbvE7dSdcksi6ibcSE6Gp485XdwxEL5igSDUxPYzVbB2jSiTY0gy2OnMUA4IotLnHhMYpuoIHlsaR+FxOJ8ty+cWKT261yOuiEo4E/atBxMEs1Qcj4Yh3ikobR/dF7KRTtfFEuQYqUjLB3CSNgZFUXqhQuRSg35wHYGqjqgJK0IhfwJRRgIzgEnhoQ9a/scrv6UJmdPKcLZJgoLcYkcPpz/dnDrl2/OkgUt/AxJ4sCNtSie8/CW6aWknnnlsn2oK8fev8AdOgeonid8PoBnV+kOCBpvuYWw5QAXwFcpPAoni3IlYlCKMsAeoDuC0uzQCsp2IlmlUgaqzQ+CTfPavgUMfG0OzXDEkvtx1ggNn8p9w4gtnx2fwZbWmSJirsO7XS8Qs7Q3p9XTC2SYlfnFv7tn2UWgE1Wmgxnhd7hdVJcM4=
