sudo: required
services:
- docker
env:
  global:
  - VERSIONS="4,6,7"
  - secure: 1D4L0AKxUlF86VrEHEGMVpm5McF5nmTaZQe4dfgNkWUc/kruQdET26c1svTLPx1oVxg2aQ2xptIgLA2zYHwben/RuDlcarRZr4wCxffeshhBkGs2MJnnJJwCBDjzkhDMwVITH5LMR3WzeQx7Pvs8fC3dYKuFcxW6iIxybX20/dzNBVjBWAcMbV8agBtnS+wp94BEH4J/aP5Rmjjah7wUvtTozqvJJjc1QXtvIwBBioF73U0O1501ekwwdlu+7UM00LRwK1eYsdK1kLxME+eQEtZaLglnO4tnekNTrcf26z835/K26yVeWddDp8MPrI+N0fbytNhZfWkNDZW5p2h25NtNYi6JmorB+64rGnJEA2eCDJxWQeuea4Xn1HBc5Yef6fyBCp8tZxm2uQxDXacWSk5NFBortANphrG+fO8BhXRkQYG8XwIfVvdYhXWFzMAfn59aF4VuXZNyOIm/xvJJPB+TIgXnxAb+5KbWGxiQb43sfoPEDVCi5hoDssQ6iVgf1Ga8R9M7q2+JLxE0A0P2TCGJLD4O1Y9tFS2oiHRWOkzSZqXIcwjd+ko3kS4BwfInkRbcEPMKDR7CjQpIE6BWhoQuDNy8E58svmVNP0yAY8x1nJxICFNHenpEv/QGIh4740eODko/5XuSvFW+pG7AofF1FFP9EkZci8JCWnKON38=
script:
- ". test/run"
notifications:
  slack:
    secure: v89QkLRc5uoo6kIj8lX+FcWg9BGCEmuugiPee1awwR8gDSgxj/2pvqCpTwNFW3fdYA3B860A4ZeHrtg8lzsvjV58Xff1pQBxxolUzMVRmHgb6eR/visAm7rov51zg9p6ebbCG/MSGUyMOHTOYUv2LV3JyjlqYdK7LyJPpRuP6rEjyDYj6R1br2zjMSN995DgImh1lXeX5E/xx1be2XejwtBOmCs0pLwHWGvcleJk0R9KvJjMov59Skb/ICH8DndyUrq+AqidyUylvrN2QMvR165NKxdPwTfG+2gH6FWI/J3LvECGFC5hJFeqB5xpSweSoGT5xgMjteygfStPfXlD1FhQ6qv2ipYGPDQSwg25WjIK9zt4m0xVEHXWC/fSMKKLXMm17Xmf0gn8/aS0K+iSpkdANIDB/YUp5xONCUdw03CgqD7mR/FDLpkanV7imx2lHWvG3Uv3LhNVVtPgVkVcRPKrrqv48O/NbY7NpSW3e30g6mcEJGghxvCZC6pQ9r32JBtYKj/O0i7+FC8VGVjePQdP1Vo3JhLdCUXX7yQqMzxAEjJidbK+lf41Bv4lndeISKB30xC21AkmdLX7MWGZUZzf7yrrC/0+nxGFrr5mkNJ9YPLBRTe8yBeb3inS5aOzEMcgaKo1fE7Jg3heeXypKomI4ooJAuf7YGV+5/+Oly4=
